spring:
  application:
    name: everest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

auth:
  grpc:
    host: ${AUTH_GRPC_HOST:localhost}
    port: ${AUTH_GRPC_PORT:9090}
    secure: ${AUTH_GRPC_SECURE:false}